"""empty message

Revision ID: 24e9aaefafd6
Revises: 
Create Date: 2019-08-02 13:27:03.114348

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '24e9aaefafd6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_\u5957\u52292\u53f7_id', table_name='套利2号')
    op.drop_table('套利2号')
    op.drop_index('ix_\u5957\u52291\u53f7_id', table_name='套利1号')
    op.drop_table('套利1号')
    op.drop_index('ix_\u7a33\u50651\u53f7_id', table_name='稳健1号')
    op.drop_table('稳健1号')
    op.add_column('private_placement', sa.Column('pp_futures_scale', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('private_placement', 'pp_futures_scale')
    op.create_table('稳健1号',
    sa.Column('id', mysql.BIGINT(display_width=20), autoincrement=False, nullable=True),
    sa.Column('产品名称', mysql.VARCHAR(charset='utf8', collation='utf8_general_ci', length=255), nullable=True),
    sa.Column('时间', sa.DATE(), nullable=True),
    sa.Column('单位净值', mysql.FLOAT(), nullable=True),
    sa.Column('累计净值', mysql.FLOAT(), nullable=True),
    sa.Column('分红标注', mysql.FLOAT(), nullable=True),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_\u7a33\u50651\u53f7_id', '稳健1号', ['id'], unique=False)
    op.create_table('套利1号',
    sa.Column('id', mysql.BIGINT(display_width=20), autoincrement=False, nullable=True),
    sa.Column('产品名称', mysql.VARCHAR(charset='utf8', collation='utf8_general_ci', length=255), nullable=True),
    sa.Column('时间', sa.DATE(), nullable=True),
    sa.Column('单位净值', mysql.FLOAT(), nullable=True),
    sa.Column('累计净值', mysql.FLOAT(), nullable=True),
    sa.Column('分红标注', mysql.FLOAT(), nullable=True),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_\u5957\u52291\u53f7_id', '套利1号', ['id'], unique=False)
    op.create_table('套利2号',
    sa.Column('id', mysql.BIGINT(display_width=20), autoincrement=False, nullable=True),
    sa.Column('产品名称', mysql.VARCHAR(charset='utf8', collation='utf8_general_ci', length=255), nullable=True),
    sa.Column('时间', sa.DATE(), nullable=True),
    sa.Column('累计净值', mysql.FLOAT(), nullable=True),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_\u5957\u52292\u53f7_id', '套利2号', ['id'], unique=False)
    # ### end Alembic commands ###
