"""empty message

Revision ID: 8742ac1f3694
Revises: 24e9aaefafd6
Create Date: 2019-08-06 10:37:59.543164

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8742ac1f3694'
down_revision = '24e9aaefafd6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('detail', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'detail')
    # ### end Alembic commands ###
